apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

commonLabels:
  env: prod

patchesJson6902:
- target:
    version: v1
    kind: Deployment
    name: app
  path: replicaSetPatch.yml